### ISSUE TITLE
AssertionError

### ISSUE THREAD

**Issue by TheChemicalWorkshop** [nikeee/sparkasse-backup-decrypt#1]
`  File "/root/temp/sparkasse/sparkasse-backup-decrypt/key.py", line 17, in extract_key_from_shared_prefs
    assert len(sf1) == 0x18`
    
can't get it to work, the password is correct however...
when i try wrong password it does the same thing?
maybe because i have fingerprint enabled? but im using the password that works (if my finger does not..)

ideas? i'd like it working

**Comment by TheChemicalWorkshop** [comment]
commented the assert out (because looks unnesecary?) now i got 
`  File "/root/anaconda3/envs/sparkasse/lib/python3.10/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats`

tried another (old) database and have the same error (no assert error on old db)

**Comment by TheChemicalWorkshop** [comment]
ok update 3

i guess my python version is wrong, anyways used pycryptodome instead of pycrypto

`  File "/root/anaconda3/envs/sparkasse/lib/python3.10/site-packages/Crypto/Cipher/_mode_cbc.py", line 287, in _create_cbc_cipher
    raise ValueError("Incorrect IV length (it must be %d bytes long)" %
ValueError: Incorrect IV length (it must be 16 bytes long)`

could downgrade my python if it's still python related

**Comment by TheChemicalWorkshop** [comment]
downgraded to python 3.8 and got ` File "/root/anaconda3/envs/sparkasse/lib/python3.8/site-packages/Crypto/Cipher/blockalgo.py", line 141, in __init__
    self._cipher = factory.new(key, *args, **kwargs)
ValueError: IV must be 16 bytes long` (the assertion error aswell)
also using pycrypto again

**Comment by nikeee** [comment]
I've re-written this project in a different language, you can try to use that instead.

If you don't have rust installed, you can download a build artifact from here:
https://github.com/nikeee/sparkasse-backup-decrypt/actions/runs/3303901846

**Comment by TheChemicalWorkshop** [comment]
yeeah wrong OS for me, i'll download rust (or maybe find a container) and compile myself, will let you know

**Comment by TheChemicalWorkshop** [comment]
after some time getting rust to work... and failing... just used another system that did support your exec

`thread 'main' panicked at 'Unable read shared prefs', src/main.rs:41:96
stack backtrace:
   0:     0x55cfe7bbd9dd - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55cfe7bbd9dd - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cfe7bbd9dd - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55cfe7bbd9dd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55cfe7bde08c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x55cfe7bbb6f1 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x55cfe7bbf0b5 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55cfe7bbf0b5 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55cfe7bbf0b5 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x55cfe7bbedd1 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x55cfe7bbf646 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
  11:     0x55cfe7bbf537 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
  12:     0x55cfe7bbded4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55cfe7bbf269 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  14:     0x55cfe7862f63 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  15:     0x55cfe7872091 - core::panicking::panic_display::hb484ed3b74a3492a
  16:     0x55cfe787374a - sparkasse_backup_decrypt::main::heaab762b7536a8b7
  17:     0x55cfe7868493 - std::sys_common::backtrace::__rust_begin_short_backtrace::h45a85581bf6b3c03
  18:     0x55cfe786c9a9 - std::rt::lang_start::{{closure}}::h5c241fe8a4ed1547
  19:     0x55cfe7bb787e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  20:     0x55cfe7bb787e - std::panicking::try::do_call::h84ca51609826746f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  21:     0x55cfe7bb787e - std::panicking::try::hd58075e533b8e0cb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  22:     0x55cfe7bb787e - std::panic::catch_unwind::h1ebac24d83cb6ce2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  23:     0x55cfe7bb787e - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  24:     0x55cfe7bb787e - std::panicking::try::do_call::h7630182e534a0a32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  25:     0x55cfe7bb787e - std::panicking::try::h05b6544f0c6331dc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  26:     0x55cfe7bb787e - std::panic::catch_unwind::h77b2ba8fd3309f34
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  27:     0x55cfe7bb787e - std::rt::lang_start_internal::h6612c8a7a6861b8b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  28:     0x55cfe7874fe2 - main
  29:     0x7f667c9d6083 - __libc_start_main
  30:     0x55cfe786320e - _start
  31:                0x0 - <unknown>`
  
  im unsure, when i open the archive i extracted from phone
  i can see files:
- StarMoneyPrefs
- googleAnalytics
- alarm
- \data\user\0\com.starfinanz.smob.android.sfinanzstatus\databases\data.db
so it all looks correct to me
im considering reinstalling the app, what do you think?

**Comment by nikeee** [comment]
Are you using the Android application? I just created a backup and ran it through (v6.3.1, build 59254) and it seems to work for me.

Could you unzip the file and do a `grep -a "sf1" StarMoneyPrefs` and `grep -a "sf3" StarMoneyPrefs` and see if the binary file matches? Just post if it matches, not the contents, as the secrets that are used to encrypt the DB are next to these strings.

Alternatively, open the file in a text editor? It looks like this:
![image](https://user-images.githubusercontent.com/4068864/197364317-e43d561c-679f-4505-9626-c54832c69f07.png)
![image](https://user-images.githubusercontent.com/4068864/197364332-ca6566a0-dfc0-4f0e-8616-6d1cdea1084a.png)

**Comment by TheChemicalWorkshop** [comment]
yupp, android
arround the start
![grafik](https://user-images.githubusercontent.com/45603583/197364671-af191fe1-2a62-4a70-ba3e-950e93744b26.png)

arround the end
![grafik](https://user-images.githubusercontent.com/45603583/197364686-a72dc8c9-7fcd-48e9-a177-c0dde9874a61.png)

i wont provide the full file however

**Comment by nikeee** [comment]
Could you replace:
```rust
    let sf1 = read_shared_preferences_entry(shared_preferences, b"sf1")?;
    if sf1.len() != 0x18 {
        return None;
    }

    // sf3 holds the encrypted database key
    let sf3 = read_shared_preferences_entry(shared_preferences, b"sf3")?;
    if sf3.len() != 0x40 {
        return None;
    }
```
with this:
```rust
    let sf1 = read_shared_preferences_entry(shared_preferences, b"sf1")?;
    println!("{:?}", sf1.len());
    if sf1.len() != 0x18 {
        return None;
    }

    // sf3 holds the encrypted database key
    let sf3 = read_shared_preferences_entry(shared_preferences, b"sf3")?;
    println!("{:?}", sf3.len());
    if sf3.len() != 0x40 {
        return None;
    }
```

And re-compile? Just makign sure that the keys have the correct length.

**Comment by TheChemicalWorkshop** [comment]
can you recompile pls? i dont have rust installed, just same exec likke in the build is fine

**Comment by TheChemicalWorkshop** [comment]
went thru older databased and got one working, but it's from 2021... goes back 2016 tho !
weirdly some are called 
sfinanzstatusMigration73000Man20221021-232756
and some
sfinanzstatus42301Man20171030-173121

just weird, your still a wizard for getting it working lol

**Comment by TheChemicalWorkshop** [comment]
hey hey i got different errors with older databases...
sfinanzstatusMigration73000Man20221021-232756.zip

`thread 'main' panicked at 'Unable read shared prefs', src/main.rs:41:96
stack backtrace:
   0:     0x55cdb55cc9dd - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55cdb55cc9dd - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55cdb55cc9dd - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55cdb55cc9dd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55cdb55ed08c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x55cdb55ca6f1 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x55cdb55ce0b5 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55cdb55ce0b5 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55cdb55ce0b5 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x55cdb55cddd1 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x55cdb55ce646 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
  11:     0x55cdb55ce537 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
  12:     0x55cdb55cced4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55cdb55ce269 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  14:     0x55cdb5271f63 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  15:     0x55cdb5281091 - core::panicking::panic_display::hb484ed3b74a3492a
  16:     0x55cdb528274a - sparkasse_backup_decrypt::main::heaab762b7536a8b7
  17:     0x55cdb5277493 - std::sys_common::backtrace::__rust_begin_short_backtrace::h45a85581bf6b3c03
  18:     0x55cdb527b9a9 - std::rt::lang_start::{{closure}}::h5c241fe8a4ed1547
  19:     0x55cdb55c687e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  20:     0x55cdb55c687e - std::panicking::try::do_call::h84ca51609826746f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  21:     0x55cdb55c687e - std::panicking::try::hd58075e533b8e0cb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  22:     0x55cdb55c687e - std::panic::catch_unwind::h1ebac24d83cb6ce2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  23:     0x55cdb55c687e - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  24:     0x55cdb55c687e - std::panicking::try::do_call::h7630182e534a0a32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  25:     0x55cdb55c687e - std::panicking::try::h05b6544f0c6331dc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  26:     0x55cdb55c687e - std::panic::catch_unwind::h77b2ba8fd3309f34
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  27:     0x55cdb55c687e - std::rt::lang_start_internal::h6612c8a7a6861b8b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  28:     0x55cdb5283fe2 - main
  29:     0x7fc1a9bfc083 - __libc_start_main
  30:     0x55cdb527220e - _start
  31:                0x0 - <unknown>`
  
  sfinanzstatusMigration42101Man20170921-072831.zip
  
  `hread 'main' panicked at 'Unable to attach output database', src/main.rs:48:29
stack backtrace:
   0:     0x5578598e09dd - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5578598e09dd - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5578598e09dd - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5578598e09dd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55785990108c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x5578598de6f1 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x5578598e20b5 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x5578598e20b5 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x5578598e20b5 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x5578598e1dd1 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x5578598e2646 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
  11:     0x5578598e2537 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
  12:     0x5578598e0ed4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x5578598e2269 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  14:     0x557859585f63 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  15:     0x557859595091 - core::panicking::panic_display::hb484ed3b74a3492a
  16:     0x5578595967e7 - sparkasse_backup_decrypt::main::heaab762b7536a8b7
  17:     0x55785958b493 - std::sys_common::backtrace::__rust_begin_short_backtrace::h45a85581bf6b3c03
  18:     0x55785958f9a9 - std::rt::lang_start::{{closure}}::h5c241fe8a4ed1547
  19:     0x5578598da87e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  20:     0x5578598da87e - std::panicking::try::do_call::h84ca51609826746f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  21:     0x5578598da87e - std::panicking::try::hd58075e533b8e0cb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  22:     0x5578598da87e - std::panic::catch_unwind::h1ebac24d83cb6ce2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  23:     0x5578598da87e - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  24:     0x5578598da87e - std::panicking::try::do_call::h7630182e534a0a32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  25:     0x5578598da87e - std::panicking::try::h05b6544f0c6331dc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  26:     0x5578598da87e - std::panic::catch_unwind::h77b2ba8fd3309f34
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  27:     0x5578598da87e - std::rt::lang_start_internal::h6612c8a7a6861b8b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  28:     0x557859597fe2 - main
  29:     0x7fd5e72d4083 - __libc_start_main
  30:     0x55785958620e - _start
  31:                0x0 - <unknown>`
  (gave me empty database)
  
  sfinanzstatus42301Man20171030-173121.zip
  
  `thread 'main' panicked at 'Unable to attach output database', src/main.rs:48:29
stack backtrace:
   0:     0x55aa03dd29dd - std::backtrace_rs::backtrace::libunwind::trace::h9135f25bc195152c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x55aa03dd29dd - std::backtrace_rs::backtrace::trace_unsynchronized::h015ee85be510df51
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x55aa03dd29dd - std::sys_common::backtrace::_print_fmt::h5fad03caa9652a2c
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x55aa03dd29dd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h2b42ca28d244e5c7
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x55aa03df308c - core::fmt::write::h401e827d053130ed
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/fmt/mod.rs:1198:17
   5:     0x55aa03dd06f1 - std::io::Write::write_fmt::hffec93268f5cde32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/io/mod.rs:1672:15
   6:     0x55aa03dd40b5 - std::sys_common::backtrace::_print::h180c4c706ee1d3fb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x55aa03dd40b5 - std::sys_common::backtrace::print::hd0c35d18765761c9
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x55aa03dd40b5 - std::panicking::default_hook::{{closure}}::h1f023310983bc730
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:295:22
   9:     0x55aa03dd3dd1 - std::panicking::default_hook::h188fec3334afd5be
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:314:9
  10:     0x55aa03dd4646 - std::panicking::rust_panic_with_hook::hf26e9d4f97b40096
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:698:17
  11:     0x55aa03dd4537 - std::panicking::begin_panic_handler::{{closure}}::hfab912107608087a
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:588:13
  12:     0x55aa03dd2ed4 - std::sys_common::backtrace::__rust_end_short_backtrace::h434b685ce8d9965b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/sys_common/backtrace.rs:138:18
  13:     0x55aa03dd4269 - rust_begin_unwind
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:584:5
  14:     0x55aa03a77f63 - core::panicking::panic_fmt::ha6dc7f2ab2479463
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/panicking.rs:142:14
  15:     0x55aa03a87091 - core::panicking::panic_display::hb484ed3b74a3492a
  16:     0x55aa03a887e7 - sparkasse_backup_decrypt::main::heaab762b7536a8b7
  17:     0x55aa03a7d493 - std::sys_common::backtrace::__rust_begin_short_backtrace::h45a85581bf6b3c03
  18:     0x55aa03a819a9 - std::rt::lang_start::{{closure}}::h5c241fe8a4ed1547
  19:     0x55aa03dcc87e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hcdfee62722e5e4b8
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/core/src/ops/function.rs:280:13
  20:     0x55aa03dcc87e - std::panicking::try::do_call::h84ca51609826746f
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  21:     0x55aa03dcc87e - std::panicking::try::hd58075e533b8e0cb
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  22:     0x55aa03dcc87e - std::panic::catch_unwind::h1ebac24d83cb6ce2
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  23:     0x55aa03dcc87e - std::rt::lang_start_internal::{{closure}}::h0145388a1edd1640
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:48
  24:     0x55aa03dcc87e - std::panicking::try::do_call::h7630182e534a0a32
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:492:40
  25:     0x55aa03dcc87e - std::panicking::try::h05b6544f0c6331dc
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panicking.rs:456:19
  26:     0x55aa03dcc87e - std::panic::catch_unwind::h77b2ba8fd3309f34
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/panic.rs:137:14
  27:     0x55aa03dcc87e - std::rt::lang_start_internal::h6612c8a7a6861b8b
                               at /rustc/a55dd71d5fb0ec5a6a3a9e8c27b2127ba491ce52/library/std/src/rt.rs:128:20
  28:     0x55aa03a89fe2 - main
  29:     0x7fb5b7632083 - __libc_start_main
  30:     0x55aa03a7820e - _start
  31:                0x0 - <unknown>`
  
kinda hoped the 2017 one was working so i could get the bank statements basically when my account was first created, that would be cool xd

**Comment by TheChemicalWorkshop** [comment]
my friend compiled the change for me

`thread 'main' panicked at 'Unable read shared prefs', src/main.rs:41:96`

can't get more info, but looks like same issue (with the 2022 file)

also same issues with the older files

**Comment by nikeee** [comment]
Let me try installing the app on a different phone to see if something has changed drastically.

What version of Android do you have?

Just to make sure: You actually have an app password set?

**Comment by TheChemicalWorkshop** [comment]
Samsung Galaxy s8 android 9

yes, i have fingerprint/password
i log in using fingerprint but i can press password and enter my password (i tried, it works)

**Comment by TheChemicalWorkshop** [comment]
Samsung Galaxy s8 android 9

yes, i have fingerprint/password
i log in using fingerprint but i can press password and enter my password (i tried, it works)

**Comment by ju6ge** [comment]
As a note this issue might have also been related to #78 😉
